[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "858cd7ded8156b94aae719650397d091bd78c4dc"
libc = "glibc"
os = "linux"

    [[HIP.download]]
    sha256 = "2f964f5383e7737c161f5af2909229598f245f8de5a486fc24bc2e64de6e9c90"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.2.0+2/HIP.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3bf2f67cb62eec9e2a78102ed1bd7da180237f4"
libc = "musl"
os = "linux"

    [[HIP.download]]
    sha256 = "dcd66cb1d37602a7ecb944408b43b10449ccbbba802971cdc030072023ca6d7b"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.2.0+2/HIP.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
