[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b32fa73ccec971e3a5e8a27be1393abf45acc228"
libc = "glibc"
os = "linux"

    [[HIP.download]]
    sha256 = "8ee2af9c2aca807931fb7095a553debf5b2cc28277ed02023638db05ba5ba4d9"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.5.2+0/HIP.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90365d6fc15a477abccb2795867da4f7e2b42499"
libc = "musl"
os = "linux"

    [[HIP.download]]
    sha256 = "6f15c094ed1604be57f1e15e09c0ed1453b0886ecffbcb0a2393f2346f81853e"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.5.2+0/HIP.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"
