[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed614f8f3ce8561867598b87a86417a8d4f9b053"
libc = "glibc"
os = "linux"

    [[HIP.download]]
    sha256 = "5e68e5aabf3a9e899a9f4161906934648967b5b55b853cd4e3e41b73fb7e7259"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v5.2.3+3/HIP.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cedbba0b5397ef843d6fdec15373e76fee316a5c"
libc = "musl"
os = "linux"

    [[HIP.download]]
    sha256 = "caccbc2b0834b3b7cc5b5215102bc8d8ab19f58d3ee5add7a3be6258c71bb3b0"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v5.2.3+3/HIP.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"
