[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e4a5c18581a48180ab1525d3d490a2e2552616f"
libc = "glibc"
os = "linux"

    [[HIP.download]]
    sha256 = "dffb8c12735c6a516e1467117ee4efb1b3c97fe07a303a5c4d5086031fefe499"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v5.4.4+0/HIP.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9d02cec0574e2215a1327b51730cdf204a03377"
libc = "musl"
os = "linux"

    [[HIP.download]]
    sha256 = "8a3e12bb82220dc72a7ee399b03abaad78ba5b749174a69fd5e1a1789fe87b78"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v5.4.4+0/HIP.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
