[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d9f7c7d930dd5c775fb94dc4e43a121232b212f"
libc = "glibc"
os = "linux"

    [[HIP.download]]
    sha256 = "f612c7f37119eaeff5bde6da9d8df70e72c3fa0274d08f39362a18d1d25b5a8f"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.2.0+1/HIP.v4.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HIP]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "845294e5a169eb79ecaf4b28161d9be6ef34b072"
libc = "musl"
os = "linux"

    [[HIP.download]]
    sha256 = "bed83d52f77b565f17337a4e40f68354e53b5e676b85fbb654f093c78fe8e5cb"
    url = "https://github.com/JuliaBinaryWrappers/HIP_jll.jl/releases/download/HIP-v4.2.0+1/HIP.v4.2.0.x86_64-linux-musl-cxx11.tar.gz"
